export interface Subject {
  code: string;
  name: string;
  credits: number;
}

export type Grade = 'S' | 'A+' | 'A' | 'B+' | 'B' | 'C' | 'P' | 'F' | '';

export const GRADE_POINTS: Record<Exclude<Grade, ''>, number> = {
  'S': 10,
  'A+': 9,
  'A': 8.5,
  'B+': 8,
  'B': 7,
  'C': 6,
  'P': 5,
  'F': 0,
};

export const BRANCHES = [
  { id: 'cse', name: 'B.Tech Computer Science' },
  { id: 'me', name: 'B.Tech Mechanical' },
  { id: 'ce', name: 'B.Tech Civil' },
  { id: 'ee', name: 'B.Tech Electrical' },
  { id: 'ec', name: 'B.Tech Electronics' },
  { id: 'general', name: 'General / Custom KTU Calculator' },
] as const;

export type BranchId = typeof BRANCHES[number]['id'];

// Common subjects for S1 & S2 (2019 Scheme)
const SEMESTER_ONE_COMMON: Subject[] = [
  { code: 'MAT 101', name: 'Linear Algebra and Calculus', credits: 4 },
  { code: 'PHT 100/CYT 100', name: 'Engineering Physics/Chemistry', credits: 4 },
  { code: 'EST 100', name: 'Engineering Mechanics', credits: 3 },
  { code: 'EST 130', name: 'Basics of Electrical & Electronics Engineering', credits: 3 },
  { code: 'HUN 101', name: 'Life Skills', credits: 2 },
  { code: 'PHL 120/CYL 120', name: 'Engineering Physics/Chemistry Lab', credits: 1 },
  { code: 'ESL 130', name: 'Electrical & Electronics Workshop', credits: 1 },
];

const SEMESTER_TWO_COMMON: Subject[] = [
  { code: 'MAT 102', name: 'Vector Calculus, Differential Equations and Transforms', credits: 4 },
  { code: 'PHT 100/CYT 100', name: 'Engineering Physics/Chemistry', credits: 4 },
  { code: 'EST 110', name: 'Engineering Graphics', credits: 3 },
  { code: 'EST 120', name: 'Basics of Civil & Mechanical Engineering', credits: 3 },
  { code: 'HUN 102', name: 'Professional Communication', credits: 2 },
  { code: 'ESL 120', name: 'Civil & Mechanical Workshop', credits: 1 },
  { code: 'PHL 120/CYL 120', name: 'Engineering Physics/Chemistry Lab', credits: 1 },
];

export const SUBJECT_TEMPLATES: Record<BranchId, Record<number, Subject[]>> = {
  cse: {
    1: SEMESTER_ONE_COMMON,
    2: SEMESTER_TWO_COMMON,
    3: [
      { code: 'MAT 203', name: 'Discrete Mathematical Structures', credits: 4 },
      { code: 'CST 201', name: 'Data Structures', credits: 4 },
      { code: 'CST 203', name: 'Logic System Design', credits: 4 },
      { code: 'CST 205', name: 'Object Oriented Programming using Java', credits: 4 },
      { code: 'HUT 200', name: 'Professional Ethics', credits: 2 },
      { code: 'MCN 201', name: 'Sustainable Engineering', credits: 0 },
      { code: 'CSL 201', name: 'Data Structures Lab', credits: 2 },
      { code: 'CSL 203', name: 'Object Oriented Programming Lab (in Java)', credits: 2 },
    ],
    4: [
      { code: 'MAT 206', name: 'Graph Theory', credits: 4 },
      { code: 'CST 202', name: 'Computer Organization and Architecture', credits: 4 },
      { code: 'CST 204', name: 'Database Management Systems', credits: 4 },
      { code: 'CST 206', name: 'Operating Systems', credits: 4 },
      { code: 'EST 200', name: 'Design and Engineering', credits: 2 },
      { code: 'MCN 202', name: 'Constitution of India', credits: 0 },
      { code: 'CSL 202', name: 'Digital Lab', credits: 2 },
      { code: 'CSL 204', name: 'Operating Systems Lab', credits: 2 },
    ],
    5: [
      { code: 'CST 301', name: 'Formal Languages and Automata Theory', credits: 4 },
      { code: 'CST 303', name: 'Computer Networks', credits: 4 },
      { code: 'CST 305', name: 'System Software', credits: 4 },
      { code: 'CST 307', name: 'Microprocessors and Microcontrollers', credits: 4 },
      { code: 'CST 309', name: 'Management of Software Systems', credits: 3 },
      { code: 'MCN 301', name: 'Disaster Management', credits: 0 },
      { code: 'CSL 331', name: 'System Software and Microprocessors Lab', credits: 2 },
      { code: 'CSL 333', name: 'Database Management Systems Lab', credits: 2 },
    ],
    6: [
      { code: 'CST 302', name: 'Compiler Design', credits: 4 },
      { code: 'CST 304', name: 'Computer Graphics and Image Processing', credits: 4 },
      { code: 'CST 306', name: 'Algorithm Analysis and Design', credits: 4 },
      { code: 'HUT 300', name: 'Industrial Economics and Foreign Trade', credits: 3 },
      { code: 'CST 308', name: 'Comprehensive Course Work', credits: 1 },
      { code: 'CSL 332', name: 'Networking Lab', credits: 2 },
      { code: 'CSD 334', name: 'Mini Project', credits: 2 },
    ],
    7: [
      { code: 'CST 401', name: 'Artificial Intelligence', credits: 4 },
      { code: 'CST Elective 2', name: 'Program Elective II', credits: 3 },
      { code: 'CST Elective 3', name: 'Open Elective', credits: 3 },
      { code: 'MCN 401', name: 'Industrial Safety Engineering', credits: 0 },
      { code: 'CSL 411', name: 'Compiler Lab', credits: 2 },
      { code: 'CSQ 413', name: 'Seminar', credits: 2 },
      { code: 'CSD 415', name: 'Project Phase I', credits: 2 },
    ],
    8: [
      { code: 'CST 402', name: 'Distributed Computing', credits: 3 },
      { code: 'CST Elective 3', name: 'Program Elective III', credits: 3 },
      { code: 'CST Elective 4', name: 'Program Elective IV', credits: 3 },
      { code: 'CST Elective 5', name: 'Program Elective V', credits: 3 },
      { code: 'CSV 414', name: 'Comprehensive Viva Voce', credits: 1 },
      { code: 'CSD 416', name: 'Project Phase II', credits: 4 },
    ]
  },
  me: {
    1: SEMESTER_ONE_COMMON,
    2: SEMESTER_TWO_COMMON,
    3: [
      { code: 'MAT 201', name: 'PDE and Complex Analysis', credits: 4 },
      { code: 'MET 201', name: 'Mechanics of Solids', credits: 4 },
      { code: 'MET 203', name: 'Mechanics of Fluids', credits: 4 },
      { code: 'MET 205', name: 'Metallurgy and Material Science', credits: 3 },
      { code: 'MCN 201', name: 'Sustainable Engineering', credits: 0 },
      { code: 'MEL 201', name: 'Computer Aided Machine Drawing', credits: 2 },
      { code: 'MEL 203', name: 'Materials Testing Lab', credits: 2 },
    ],
    4: [
      { code: 'MAT 202', name: 'Probability, Statistics and Numerical Methods', credits: 4 },
      { code: 'MET 202', name: 'Engineering Thermodynamics', credits: 4 },
      { code: 'MET 204', name: 'Manufacturing Process', credits: 4 },
      { code: 'MET 206', name: 'Fluid Machinery', credits: 4 },
      { code: 'EST 200', name: 'Design and Engineering', credits: 2 },
      { code: 'MCN 202', name: 'Constitution of India', credits: 0 },
      { code: 'MEL 202', name: 'Thermal Engineering Lab-I', credits: 2 },
      { code: 'MEL 204', name: 'Fluid Mechanics and Machines Lab', credits: 2 },
    ],
    5: [
      { code: 'MET 301', name: 'Mechanics of Machinery', credits: 4 },
      { code: 'MET 303', name: 'Thermal Engineering-II', credits: 4 },
      { code: 'MET 305', name: 'Industrial Economics and Foreign Trade', credits: 3 },
      { code: 'MET 307', name: 'Machine Tools and Metrology', credits: 3 },
      { code: 'MCN 301', name: 'Disaster Management', credits: 0 },
      { code: 'MEL 331', name: 'Machine Tools Lab-I', credits: 2 },
      { code: 'MEL 333', name: 'Thermal Engineering Lab-II', credits: 2 },
    ],
    6: [
      { code: 'MET 302', name: 'Heat and Mass Transfer', credits: 4 },
      { code: 'MET 304', name: 'Dynamics of Machinery and Machine Design', credits: 4 },
      { code: 'MET 306', name: 'Advanced Manufacturing Engineering', credits: 4 },
      { code: 'MET Elective 1', name: 'Program Elective I', credits: 3 },
      { code: 'HUT 310', name: 'Management for Engineers', credits: 3 },
      { code: 'MET 308', name: 'Comprehensive Course Work', credits: 1 },
      { code: 'MEL 332', name: 'Computer Aided Design and Analysis Lab', credits: 2 },
      { code: 'MEL 334', name: 'Thermal Engineering Lab-II', credits: 2 },
    ],
    7: [
      { code: 'MET 401', name: 'Design of Machine Elements', credits: 4 },
      { code: 'MET Elective 2', name: 'Program Elective II', credits: 3 },
      { code: 'MET Elective 3', name: 'Open Elective', credits: 3 },
      { code: 'MCN 401', name: 'Industrial Safety Engineering', credits: 0 },
      { code: 'MEL 411', name: 'Mechanical Engineering Lab', credits: 2 },
      { code: 'MEQ 413', name: 'Seminar', credits: 2 },
      { code: 'MED 415', name: 'Project Phase I', credits: 2 },
    ],
    8: [
      { code: 'MET Elective 4', name: 'Program Elective IV', credits: 3 },
      { code: 'MET Elective 5', name: 'Program Elective V', credits: 3 },
      { code: 'MEV 414', name: 'Comprehensive Viva Voce', credits: 1 },
      { code: 'MED 416', name: 'Project Phase II', credits: 4 },
    ],
  },
  ce: {
    1: SEMESTER_ONE_COMMON,
    2: SEMESTER_TWO_COMMON,
    3: [
      { code: 'MAT 201', name: 'PDE and Complex Analysis', credits: 4 },
      { code: 'CET 201', name: 'Mechanics of Solids', credits: 4 },
      { code: 'CET 203', name: 'Fluid Mechanics and Hydraulics', credits: 4 },
      { code: 'CET 205', name: 'Surveying and Geomatics', credits: 4 },
      { code: 'MCN 201', name: 'Sustainable Engineering', credits: 0 },
      { code: 'CEL 201', name: 'Civil Engineering Planning and Drafting Lab', credits: 2 },
      { code: 'CEL 203', name: 'Survey Lab I', credits: 2 },
    ],
    4: [
      { code: 'MAT 202', name: 'Probability, Statistics and Numerical Methods', credits: 4 },
      { code: 'CET 202', name: 'Engineering Geology', credits: 4 },
      { code: 'CET 204', name: 'Geotechnical Engineering – I', credits: 4 },
      { code: 'CET 206', name: 'Transportation Engineering', credits: 4 },
      { code: 'EST 200', name: 'Design and Engineering', credits: 2 },
      { code: 'MCN 202', name: 'Constitution of India', credits: 0 },
      { code: 'CEL 202', name: 'Material Testing Lab – I', credits: 2 },
      { code: 'CEL 204', name: 'Fluid Mechanics Lab', credits: 2 },
    ],
    5: [
      { code: 'CET 301', name: 'Structural Analysis – I', credits: 4 },
      { code: 'CET 303', name: 'Geotechnical Engineering – II', credits: 4 },
      { code: 'CET 305', name: 'Design of Concrete Structures', credits: 4 },
      { code: 'CET 307', name: 'Hydrology and Water Resources Engineering', credits: 4 },
      { code: 'CET 309', name: 'Construction Technology and Management', credits: 3 },
      { code: 'MCN 301', name: 'Disaster Management', credits: 0 },
      { code: 'CEL 331', name: 'Material Testing Lab – II', credits: 2 },
      { code: 'CEL 333', name: 'Geotechnical Engineering Lab', credits: 2 },
    ],
    6: [
      { code: 'CET 302', name: 'Structural Analysis – II', credits: 4 },
      { code: 'CET 304', name: 'Environmental Engineering', credits: 4 },
      { code: 'CET 306', name: 'Design of Hydraulic Structures', credits: 4 },
      { code: 'CET Elective 1', name: 'Program Elective I', credits: 3 },
      { code: 'HUT 300', name: 'Industrial Economics and Foreign Trade', credits: 3 },
      { code: 'CET 308', name: 'Comprehensive Course Work', credits: 1 },
      { code: 'CEL 332', name: 'Transportation Engineering Lab', credits: 2 },
      { code: 'CEL 334', name: 'Civil Engineering Software Lab', credits: 2 },
    ],
    7: [
      { code: 'CET 401', name: 'Design of Steel Structures', credits: 4 },
      { code: 'CET Elective 2', name: 'Program Elective II', credits: 3 },
      { code: 'CET Elective 3', name: 'Open Elective', credits: 3 },
      { code: 'MCN 401', name: 'Industrial Safety Engineering', credits: 0 },
      { code: 'CEL 411', name: 'Environmental Engg Lab', credits: 2 },
      { code: 'CEQ 413', name: 'Seminar', credits: 2 },
      { code: 'CED 415', name: 'Project Phase I', credits: 2 },
    ],
    8: [
      { code: 'CET 402', name: 'Quantity Surveying and Valuation', credits: 3 },
      { code: 'CET Elective 4', name: 'Program Elective IV', credits: 3 },
      { code: 'CET Elective 5', name: 'Program Elective V', credits: 3 },
      { code: 'CEV 414', name: 'Comprehensive Viva Voce', credits: 1 },
      { code: 'CED 416', name: 'Project Phase II', credits: 4 },
    ],
  },
  ee: {
    1: SEMESTER_ONE_COMMON,
    2: SEMESTER_TWO_COMMON,
    3: [
      { code: 'MAT 201', name: 'PDE and Complex Analysis', credits: 4 },
      { code: 'EET 201', name: 'Circuits and Networks', credits: 4 },
      { code: 'EET 203', name: 'Measurements and Instrumentation', credits: 4 },
      { code: 'EET 205', name: 'Analog Electronics', credits: 4 },
      { code: 'MCN 201', name: 'Sustainable Engineering', credits: 0 },
      { code: 'EEL 201', name: 'Circuits and Measurements Lab', credits: 2 },
      { code: 'EEL 203', name: 'Analog Electronics Lab', credits: 2 },
    ],
    4: [
      { code: 'MAT 204', name: 'Probability, Random Processes and Numerical Methods', credits: 4 },
      { code: 'EET 202', name: 'DC Machines and Transformers', credits: 4 },
      { code: 'EET 204', name: 'Electromagnetic Theory', credits: 4 },
      { code: 'EET 206', name: 'Digital Electronics', credits: 4 },
      { code: 'EST 200', name: 'Design and Engineering', credits: 2 },
      { code: 'MCN 202', name: 'Constitution of India', credits: 0 },
      { code: 'EEL 202', name: 'Electrical Machines Lab I', credits: 2 },
      { code: 'EEL 204', name: 'Digital Electronics Lab', credits: 2 },
    ],
    5: [
      { code: 'EET 301', name: 'Power Systems I', credits: 4 },
      { code: 'EET 303', name: 'Signals and Systems', credits: 4 },
      { code: 'EET 305', name: 'Power Electronics', credits: 4 },
      { code: 'EET 307', name: 'Synchronous and Induction Machines', credits: 4 },
      { code: 'HUT 310', name: 'Management for Engineers', credits: 3 },
      { code: 'MCN 301', name: 'Disaster Management', credits: 0 },
      { code: 'EEL 331', name: 'Power Electronics Lab', credits: 2 },
      { code: 'EEL 333', name: 'Electrical Machines Lab II', credits: 2 },
    ],
    6: [
      { code: 'EET 302', name: 'Linear Control Systems', credits: 4 },
      { code: 'EET 304', name: 'Power Systems II', credits: 4 },
      { code: 'EET 306', name: 'Power System Analysis', credits: 4 },
      { code: 'EET Elective 1', name: 'Program Elective I', credits: 3 },
      { code: 'HUT 300', name: 'Industrial Economics and Foreign Trade', credits: 3 },
      { code: 'EET 308', name: 'Comprehensive Course Work', credits: 1 },
      { code: 'EEL 332', name: 'Power Systems Lab', credits: 2 },
      { code: 'EEL 334', name: 'Microprocessor and Embedded Systems Lab', credits: 2 },
    ],
    7: [
      { code: 'EET 401', name: 'Advanced Control Systems', credits: 4 },
      { code: 'EET Elective 2', name: 'Program Elective II', credits: 3 },
      { code: 'EET Elective 3', name: 'Open Elective', credits: 3 },
      { code: 'MCN 401', name: 'Industrial Safety Engineering', credits: 0 },
      { code: 'EEL 411', name: 'Control Systems Lab', credits: 2 },
      { code: 'EEQ 413', name: 'Seminar', credits: 2 },
      { code: 'EED 415', name: 'Project Phase I', credits: 2 },
    ],
    8: [
      { code: 'EET 402', name: 'Electrical System Design and Estimation', credits: 3 },
      { code: 'EET Elective 4', name: 'Program Elective IV', credits: 3 },
      { code: 'EET Elective 5', name: 'Program Elective V', credits: 3 },
      { code: 'EEV 414', name: 'Comprehensive Viva Voce', credits: 1 },
      { code: 'EED 416', name: 'Project Phase II', credits: 4 },
    ],
  },
  ec: {
    1: SEMESTER_ONE_COMMON,
    2: SEMESTER_TWO_COMMON,
    3: [
      { code: 'MAT 201', name: 'PDE and Complex Analysis', credits: 4 },
      { code: 'ECT 201', name: 'Solid State Devices', credits: 4 },
      { code: 'ECT 203', name: 'Network Theory', credits: 4 },
      { code: 'ECT 205', name: 'Network Theory', credits: 4 },
      { code: 'MCN 201', name: 'Sustainable Engineering', credits: 0 },
      { code: 'ECL 201', name: 'Scientific Computing Lab', credits: 2 },
      { code: 'ECL 203', name: 'Logic Design Lab', credits: 2 },
    ],
    4: [
      { code: 'MAT 204', name: 'Probability, Random Processes and Numerical Methods', credits: 4 },
      { code: 'ECT 202', name: 'Analog Circuits', credits: 4 },
      { code: 'ECT 204', name: 'Signals and Systems', credits: 4 },
      { code: 'ECT 206', name: 'Computer Architecture and Microcontrollers', credits: 4 },
      { code: 'EST 200', name: 'Design and Engineering', credits: 2 },
      { code: 'MCN 202', name: 'Constitution of India', credits: 0 },
      { code: 'ECL 202', name: 'Analog Circuits and Simulation Lab', credits: 2 },
      { code: 'ECL 204', name: 'Microcontroller Lab', credits: 2 },
    ],
    5: [
      { code: 'ECT 301', name: 'Linear Integrated Circuits', credits: 4 },
      { code: 'ECT 303', name: 'Digital Signal Processing', credits: 4 },
      { code: 'ECT 305', name: 'Analog and Digital Communication', credits: 4 },
      { code: 'ECT 307', name: 'Control Systems', credits: 4 },
      { code: 'HUT 310', name: 'Management for Engineers', credits: 3 },
      { code: 'MCN 301', name: 'Disaster Management', credits: 0 },
      { code: 'ECL 331', name: 'Analog Communication Lab', credits: 2 },
      { code: 'ECL 333', name: 'Digital Signal Processing Lab', credits: 2 },
    ],
    6: [
      { code: 'ECT 302', name: 'Electromagnetics', credits: 4 },
      { code: 'ECT 304', name: 'VLSI Circuit Design', credits: 4 },
      { code: 'ECT 306', name: 'Information Theory and Coding', credits: 4 },
      { code: 'ECT Elective 1', name: 'Program Elective I', credits: 3 },
      { code: 'HUT 300', name: 'Industrial Economics and Foreign Trade', credits: 3 },
      { code: 'ECT 308', name: 'Comprehensive Course Work', credits: 1 },
      { code: 'ECL 332', name: 'Communication Lab', credits: 2 },
      { code: 'ECD 334', name: 'Mini Project', credits: 2 },
    ],
    7: [
      { code: 'ECT 401', name: 'Microwaves and Antennas', credits: 4 },
      { code: 'ECT Elective 2', name: 'Program Elective II', credits: 3 },
      { code: 'ECT Elective 3', name: 'Open Elective', credits: 3 },
      { code: 'MCN 401', name: 'Industrial Safety Engineering', credits: 0 },
      { code: 'ECL 411', name: 'Electromagnetics Lab', credits: 2 },
      { code: 'ECQ 413', name: 'Seminar', credits: 2 },
      { code: 'ECD 415', name: 'Project Phase I', credits: 2 },
    ],
    8: [
      { code: 'ECT 402', name: 'Wireless Communication', credits: 3 },
      { code: 'ECT Elective 4', name: 'Program Elective IV', credits: 3 },
      { code: 'ECT Elective 5', name: 'Program Elective V', credits: 3 },
      { code: 'ECV 414', name: 'Comprehensive Viva Voce', credits: 1 },
      { code: 'ECD 416', name: 'Project Phase II', credits: 4 },
    ],
  },
  general: {
    1: [], 2: [], 3: [], 4: [], 5: [], 6: [], 7: [], 8: [],
  }
};
